package com.psja.CurrencyCalculator;

public class CurrencyCalculator extends javax.swing.JFrame {
    Currency currency; 
    /**
     * Creates new form CurrencyCalculator
     */
    public CurrencyCalculator() {
        initComponents();
        currency = new Currency(this);
        currency.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabTable = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTab = new javax.swing.JTable();
        jDate = new javax.swing.JLabel();
        tabConverter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboCurrencyList = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jamount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCurrencyToPLN = new javax.swing.JTable();
        jCalculateBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDate1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacja Walutowa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("App"); // NOI18N

        jLabel2.setText("Aktualne kursy walut w stosunku do PLN:");

        jTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Waluta", "Kod", "Kurs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTab.setCellSelectionEnabled(true);
        jTab.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTab);

        jDate.setText("Dane z dnia: ");

        javax.swing.GroupLayout tabTableLayout = new javax.swing.GroupLayout(tabTable);
        tabTable.setLayout(tabTableLayout);
        tabTableLayout.setHorizontalGroup(
            tabTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(tabTableLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDate)))
                .addContainerGap())
        );
        tabTableLayout.setVerticalGroup(
            tabTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kursy", tabTable);
        tabTable.getAccessibleContext().setAccessibleParent(jTabbedPane1);

        tabConverter.setPreferredSize(new java.awt.Dimension(690, 540));

        jLabel1.setText("Wybierz walutę");

        jComboCurrencyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCurrencyListActionPerformed(evt);
            }
        });

        jLabel3.setText("Podaj kwotę");

        jamount.setColumns(19);
        jamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamountActionPerformed(evt);
            }
        });

        jCurrencyToPLN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Waluta", "Kod", "Wartość"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jCurrencyToPLN.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(jCurrencyToPLN);

        jCalculateBtn.setText("Przelicz");
        jCalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalculateBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Kwota w innych walutach");

        jDate1.setText("Dane z dnia: ");

        javax.swing.GroupLayout tabConverterLayout = new javax.swing.GroupLayout(tabConverter);
        tabConverter.setLayout(tabConverterLayout);
        tabConverterLayout.setHorizontalGroup(
            tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConverterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabConverterLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDate1))
                    .addComponent(jScrollPane2)
                    .addGroup(tabConverterLayout.createSequentialGroup()
                        .addGroup(tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tabConverterLayout.createSequentialGroup()
                                .addComponent(jComboCurrencyList, 0, 221, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(tabConverterLayout.createSequentialGroup()
                                .addComponent(jamount, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCalculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        tabConverterLayout.setVerticalGroup(
            tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabConverterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCurrencyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalculateBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(tabConverterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jDate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kalkulator", tabConverter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Kursy");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamountActionPerformed
        
        
    }//GEN-LAST:event_jamountActionPerformed

    private void jCalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalculateBtnActionPerformed
        currency.calculate();
    }//GEN-LAST:event_jCalculateBtnActionPerformed

    private void jComboCurrencyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCurrencyListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCurrencyListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCalculateBtn;
    protected javax.swing.JComboBox<String> jComboCurrencyList;
    protected javax.swing.JTable jCurrencyToPLN;
    protected javax.swing.JLabel jDate;
    protected javax.swing.JLabel jDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JTable jTab;
    private javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JTextField jamount;
    private javax.swing.JPanel tabConverter;
    private javax.swing.JPanel tabTable;
    // End of variables declaration//GEN-END:variables
}
